[package]
name = "fossfox"
version = "0.1.0"
edition = "2021"

[dependencies]
console = "0.15.7"
dialoguer = "0.10.4"
serde = { version = "1.0.163", features = ["serde_derive"] }
serde_json = "1.0.96"
slugify = "0.1.0"
thiserror = "1.0.40"
